name: Release

on:
  push:
    branches:
      - main
      - release/**

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: alexandremahdhaoui/release@v0.2.1
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
